- name: SDN testbed
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt-get repo and cache 
      apt:
        update_cache: yes
        upgrade: dist 
    - name: Install packages
      apt:
        name:
          - mininet
          - openvswitch-switch
          - iperf
          - net-tools
          - curl
          - apache2
          - x264
          - gpac
          - ansible
          - ffmpeg
          - unzip
        state: present
    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Copying files
      copy:
        src: topo/
        dest: "/home/mininet/topo/"
        owner: mininet
        group: mininet
    - name: Installing dash.js
      unarchive:
        src: topo/dashjs.zip
        dest: /var/www/html/
        remote_src: no