- name: SDN testbed
  hosts: webservers
  become: yes

  tasks:
    - name: Install packages
      apt:
        name:
          - mininet
          - openvswitch-switch
          - iperf
          - net-tools
          - curl
          - apache2
          - x264
          - gpac
          - ansible
          - ffmpeg
          - unzip
          - epiphany-browser
          - gstreamer1.0-plugins-bad
          - gstreamer1.0-plugins-ugly
          - gstreamer1.0-libav
          - xterm
        state: present
        update_cache: yes
    - name: Copying files
      copy:
        src: topo/
        dest: "/home/test/topo/"
        owner: test 
        group: test 
    - name: Installing dash.js
      unarchive:
        src: topo/dashjs.zip
        dest: /var/www/html/
        remote_src: no